services:
  - type: web
    name: document-analysis-system-api
    runtime: image
    repo: https://github.com/subixx/document-analysis-system
    plan: free
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: API_SECRET_KEY
        value: sk_track2_987654321
      - key: OCR_PROVIDER
        value: tesseract
      - key: DEFAULT_LLM_MODEL
        value: llama-3.3-70b-versatile
      - key: DEBUG
        value: false
